// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly check: string
	readonly dialogContent: string
	readonly empty: string
	readonly group: string
	readonly input: string
	readonly inputGroup: string
	readonly inputWrapper: string
	readonly item: string
	readonly list: string
	readonly root: string
	readonly searchIcon: string
	readonly separator: string
	readonly shortcut: string
}
export default styles
