// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly content: string
	readonly contentBounded: string
	readonly stacked: string
	readonly stackedContent: string
	readonly stackedHeader: string
	readonly toolbar: string
	readonly toolbarEnd: string
	readonly toolbarRuled: string
	readonly toolbarStart: string
	readonly topbar: string
	readonly topbarBody: string
	readonly topbarCenter: string
	readonly topbarContent: string
	readonly topbarEnd: string
	readonly topbarHeader: string
	readonly topbarLogo: string
	readonly topbarSidebar: string
	readonly topbarStart: string
	readonly topbarTrigger: string
}
export default styles
