// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly addon: string
	readonly affordance: string
	readonly affordanceEnd: string
	readonly affordanceStart: string
	readonly affordanceText: string
	readonly affordanceTextareaEnd: string
	readonly clear: string
	readonly count: string
	readonly countOver: string
	readonly frame: string
	readonly revealButton: string
	readonly search: string
	readonly select: string
	readonly selectChevron: string
	readonly selectFrame: string
	readonly spinner: string
	readonly textarea: string
	readonly textareaFrame: string
}
export default styles
