// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly step: string
	readonly stepButton: string
	readonly stepCheck: string
	readonly stepHint: string
	readonly stepLabel: string
	readonly stepLine: string
	readonly stepMarker: string
	readonly stepRail: string
	readonly stepTarget: string
	readonly stepText: string
	readonly stepper: string
}
export default styles
