// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly body: string
	readonly content: string
	readonly dot: string
	readonly head: string
	readonly icon: string
	readonly item: string
	readonly line: string
	readonly rail: string
	readonly timeline: string
	readonly timestamp: string
}
export default styles
