// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly board: string
	readonly card: string
	readonly cardMeta: string
	readonly cardTitle: string
	readonly column: string
}
export default styles
