// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly actions: string
	readonly body: string
	readonly headerBack: string
	readonly headerBackRule: string
	readonly headerTitleIcon: string
	readonly page: string
}
export default styles
