// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly action: string
	readonly avatar: string
	readonly block: string
	readonly fact: string
	readonly factLabel: string
	readonly factValue: string
	readonly facts: string
	readonly heading: string
	readonly identity: string
	readonly identityMeta: string
	readonly identityName: string
	readonly line: string
	readonly lineLast: string
	readonly lines: string
	readonly pageHeader: string
	readonly pageHeaderActions: string
	readonly pageHeaderDescription: string
	readonly pageHeaderText: string
	readonly panel: string
	readonly root: string
	readonly table: string
	readonly tableBar: string
	readonly tableCell: string
	readonly tableFramed: string
	readonly tableHeadRow: string
	readonly tableRow: string
	readonly title: string
	readonly twoColumn: string
}
export default styles
