// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly createRow: string
	readonly empty: string
	readonly error: string
	readonly errorState: string
	readonly footer: string
	readonly list: string
	readonly loadingMore: string
	readonly option: string
	readonly optionMeta: string
	readonly popup: string
	readonly positioner: string
	readonly root: string
	readonly scroller: string
	readonly status: string
}
export default styles
