// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly container: string
	readonly indicator: string
	readonly indicatorDashed: string
	readonly indicatorLine: string
	readonly legend: string
	readonly legendItem: string
	readonly sparkline: string
	readonly tooltip: string
	readonly tooltipLabel: string
	readonly tooltipName: string
	readonly tooltipRow: string
	readonly tooltipValue: string
}
export default styles
