// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly action: string
	readonly actions: string
	readonly bottom: string
	readonly cancel: string
	readonly center: string
	readonly close: string
	readonly content: string
	readonly description: string
	readonly end: string
	readonly icon: string
	readonly spinner: string
	readonly start: string
	readonly statusError: string
	readonly statusInfo: string
	readonly statusSuccess: string
	readonly statusWarning: string
	readonly title: string
	readonly toast: string
	readonly top: string
	readonly viewport: string
}
export default styles
