// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly categoryChevron: string
	readonly categoryNav: string
	readonly categoryRow: string
	readonly group: string
	readonly groupChevron: string
	readonly groupLabel: string
	readonly groupLabelStatic: string
	readonly item: string
	readonly itemIcon: string
	readonly itemLabel: string
	readonly list: string
	readonly progress: string
	readonly progressHead: string
	readonly sectionItem: string
	readonly sectionItemNested: string
	readonly sectionNav: string
	readonly sideNav: string
}
export default styles
