// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly canvas: string
	readonly composed: string
	readonly expandedDialog: string
	readonly formColumn: string
	readonly frame: string
	readonly inlineIcon: string
}
export default styles
