// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly command: string
	readonly commandList: string
	readonly list: string
	readonly listState: string
	readonly panel: string
	readonly panelHeader: string
	readonly panelInline: string
	readonly panelQuery: string
	readonly row: string
	readonly rowIcon: string
	readonly rowText: string
	readonly tab: string
	readonly tabs: string
}
export default styles
