// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly content: string
	readonly indicator: string
	readonly link: string
	readonly list: string
	readonly popup: string
	readonly positioner: string
	readonly root: string
	readonly trigger: string
	readonly viewport: string
}
export default styles
