// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly dot: string
	readonly dotPending: string
	readonly dotPulse: string
	readonly root: string
	readonly toneDestructive: string
	readonly toneInfo: string
	readonly toneNeutral: string
	readonly tonePrimary: string
	readonly toneSecondary: string
	readonly toneSuccess: string
	readonly toneWarning: string
	readonly variantOutline: string
	readonly variantSoft: string
	readonly variantSolid: string
}
export default styles
