// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly appearanceOutline: string
	readonly appearanceSoft: string
	readonly appearanceSolid: string
	readonly dot: string
	readonly dotPending: string
	readonly dotPulse: string
	readonly root: string
}
export default styles
