/** Catalogue blocks keep edits, toggled values and tabs working, and pass axe. */
import { expect, test } from "@playwright/test"
import AxeBuilder from "@axe-core/playwright"
import { visitRoute } from "./routes"

test("catalogue blocks keep edits, toggled values and tabs", async ({ page }) => {
	const errors: string[] = []
	page.on("pageerror", error => errors.push(error.message))
	await visitRoute(page, "/blocks-catalogue")
	const seo = page.locator("#catalogue-seo")
	await seo.getByRole("button", { name: "Edit listing" }).first().click()
	const dialog = page.getByRole("dialog", { name: "Edit search appearance" })
	await dialog.getByRole("textbox", { name: "Page title" }).fill("Updated catalogue listing")
	await dialog.getByRole("button", { name: "Save changes" }).click()
	await expect(dialog).not.toBeVisible()
	await expect(seo.getByText("Updated catalogue listing", { exact: true })).toBeVisible()
	await seo.getByRole("button", { name: "Edit listing" }).first().click()
	await dialog.getByRole("textbox", { name: "Page title" }).fill("Discarded draft")
	await dialog.getByRole("button", { name: "Cancel", exact: true }).click()
	await expect(seo.getByText("Updated catalogue listing", { exact: true })).toBeVisible()
	const inventory = page.locator("#catalogue-inventory")
	const available = inventory.getByRole("textbox", { name: "Available", exact: true })
	await available.fill("37")
	await expect(inventory.locator(".inventory-section--summary")).toContainText("37")
	await inventory.getByText("Track quantity", { exact: true }).click()
	await expect(available).not.toBeVisible()
	await inventory.getByText("Track quantity", { exact: true }).click()
	await expect(available).toHaveValue("37")
	await inventory.getByText("Requires shipping", { exact: true }).click()
	await expect(inventory.getByRole("textbox", { name: "Weight" })).not.toBeVisible()
	await inventory.getByText("Requires shipping", { exact: true }).click()
	await expect(inventory.getByRole("textbox", { name: "Weight" })).toHaveValue("0.42")
	const vendors = page.locator("#catalogue-vendor")
	await vendors.getByRole("tab", { name: "Performance" }).click()
	await expect(vendors.getByText("1,284", { exact: true })).toBeVisible()
	await vendors.getByRole("tab", { name: "Overview" }).click()
	await expect(vendors.getByText("6 days", { exact: true })).toBeVisible()
	expect((await new AxeBuilder({ page }).include("main").analyze()).violations).toEqual([])
	expect(errors).toEqual([])
})
