/** Feature flows at desktop and phone widths: DataView filters and the filter sheet, mentions, and activities. */
import { expect, test } from "@playwright/test"
import AxeBuilder from "@axe-core/playwright"
import { visitRoute } from "./routes"

for (const viewport of [{ width: 1280, height: 900 }, { width: 390, height: 844 }]) {
	test.describe(`${viewport.width}px feature polish`, () => {
		test.use({ viewport })
		test("DataView filters apply and clear without losing the table", async ({ page }) => {
			await visitRoute(page, "/data-view")
			const example = page.locator("#data-view")
			if (viewport.width < 768) {
				await expect(example.getByRole("combobox", { name: "Saved views", exact: true })).toBeVisible()
				await example.getByRole("button", { name: "Filters", exact: true }).click()
				const sheet = page.getByRole("dialog", { name: "Filters", exact: true })
				await sheet.getByRole("button", { name: "Status Any" }).click()
				await sheet.getByRole("option", { name: "Confirmed", exact: true }).click()
				await sheet.getByRole("button", { name: "Apply", exact: true }).click()
				await expect(sheet.getByRole("button", { name: /Status .*Confirmed/ })).toBeFocused()
				await expect(sheet).toContainText("1 filter applied")
				expect((await new AxeBuilder({ page }).include("dialog[open]").analyze()).violations).toEqual([])
				await sheet.getByRole("button", { name: "Done", exact: true }).click()
				await expect(example.getByRole("button", { name: "Filters 1", exact: true })).toBeFocused()
				await expect(example.getByRole("table")).not.toContainText("BK-4418")
				await example.getByRole("button", { name: "Filters 1", exact: true }).click()
				await sheet.getByRole("button", { name: "Clear: Status" }).click()
				await expect(sheet).toContainText("No filters applied")
				await page.keyboard.press("Escape")
				await expect(example.getByRole("table")).toContainText("The Old Granary")
			} else {
				await example.getByRole("button", { name: "Edit: Status" }).click()
				await page.getByRole("option", { name: "Confirmed", exact: true }).click()
				await page.getByRole("button", { name: "Apply", exact: true }).click()
				await expect(example.getByRole("table")).not.toContainText("BK-4418")
				await example.getByRole("button", { name: "Clear filters" }).click()
				await expect(example.getByRole("table")).toContainText("The Old Granary")
			}
			await example.getByRole("textbox", { name: "Search", exact: true }).fill("does-not-exist")
			await expect(example.getByRole("table")).not.toContainText("Marlow Hall")
			await example.getByRole("textbox", { name: "Search", exact: true }).fill("")
			await expect(example.getByRole("table")).toContainText("Marlow Hall")
		})

		test("mentions keep the caret, navigate results and support button search", async ({ page }) => {
			await visitRoute(page, "/mentions")
			const example = page.locator("#mention-inline")
			const editor = example.getByRole("textbox")
			await editor.fill("@")
			const inline = page.locator(".mention-inline-suggestions--component")
			await expect(inline.getByRole("option")).toHaveCount(3)
			await expect(editor).toBeFocused()
			await editor.press("ArrowDown")
			await expect(inline.getByRole("option", { name: /Marcus Webb/ })).toHaveAttribute("aria-selected", "true")
			await expect(editor).toBeFocused()
			/* The suggestions stay on screen. */
			expect(await inline.evaluate(panel => panel.getBoundingClientRect().right)).toBeLessThanOrEqual(viewport.width)
			expect((await new AxeBuilder({ page }).include("#mention-inline").analyze()).violations).toEqual([])
			await editor.press("Enter")
			await expect(editor).toContainText("Marcus Webb")
			await expect(inline).toHaveCount(0)
			await editor.fill("@zzzzzz")
			await expect(inline).toContainText("No matches.")
			await editor.press("Escape")
			await expect(inline).toHaveCount(0)
			await expect(editor).toBeFocused()
			await editor.fill("")
			await example.getByRole("button", { name: "Insert reference", exact: true }).click()
			const picker = page.locator(".mention-picker--component")
			const search = picker.getByRole("combobox")
			await expect(search).toBeFocused()
			await search.fill("Alice")
			await expect(picker.getByRole("option", { name: /Alice Mercer/ })).toBeVisible()
			await search.press("ArrowDown")
			await search.press("Enter")
			await expect(picker).toHaveCount(0)
			await expect(editor).toContainText("Alice Mercer")
		})

		test("activities expand facts, run actions and preserve state during recovery", async ({ page }) => {
			await visitRoute(page, "/activities")
			const feed = page.locator("#activity-feed")
			const row = feed.locator('[data-slot="activity-row"]').first()
			await expect(row).not.toContainText("Deposit due")
			await row.getByRole("button", { name: "Show details" }).click()
			await expect(row).toContainText("Deposit due")
			await expect(row.getByRole("button", { name: "Hide details" })).toHaveAttribute("aria-controls", /.+/)
			expect((await new AxeBuilder({ page }).include("#activity-feed").analyze()).violations).toEqual([])
			await row.getByRole("button", { name: "Hide details" }).click()
			await feed.getByRole("button", { name: "Resend", exact: true }).click()
			await expect(feed).toContainText("The confirmation was delivered on retry.")
			await feed.getByRole("combobox", { name: "Feed state" }).click()
			await page.getByRole("option", { name: "Refresh failed", exact: true }).click()
			await expect(feed.getByRole("alert")).toBeVisible()
			await feed.getByRole("button", { name: "Try again" }).click()
			await expect(feed.getByRole("alert")).toHaveCount(0)
			if (viewport.width < 768) {
				const comment = page.locator("#activity-log .comment-item--component").first()
				await comment.scrollIntoViewIfNeeded()
				const outer = await comment.boundingBox()
				const content = await comment.locator(".comment-content--component").boundingBox()
				/* The comment body stays inside its row. */
				expect(content!.x + content!.width).toBeLessThanOrEqual(outer!.x + outer!.width + 1)
				await comment.getByRole("button", { name: "Comment actions", exact: true }).click()
				await expect(page.getByRole("menuitem", { name: "Delete", exact: true })).toBeVisible()
				await page.keyboard.press("Escape")
			}
		})
	})
}

test("mobile sheet preserves drafts and supports async, range, tag and date editors", async ({ page }) => {
	await page.setViewportSize({ width: 390, height: 844 })
	await visitRoute(page, "/filters")
	await page.getByRole("button", { name: "Filters 1", exact: true }).click()
	const sheet = page.getByRole("dialog", { name: "Filters", exact: true })
	await sheet.getByRole("button", { name: /Status .*Confirmed/ }).click()
	await sheet.getByRole("option", { name: "Pending", exact: true }).click()
	await sheet.getByRole("button", { name: "Back to filters" }).click()
	await expect(sheet.getByRole("button", { name: /Status .*Confirmed/ })).not.toContainText("Pending")
	await sheet.getByRole("button", { name: "Venue Any" }).click()
	await sheet.getByRole("combobox").fill("Riverside")
	await sheet.getByRole("option", { name: "Riverside Rooms", exact: true }).click()
	await sheet.getByRole("button", { name: "Apply", exact: true }).click()
	await expect(sheet.getByRole("button", { name: /Venue .*Riverside Rooms/ })).toBeFocused()
	await sheet.getByRole("button", { name: "Guests Any" }).click()
	await sheet.getByRole("spinbutton", { name: "Min" }).fill("20")
	await sheet.getByRole("spinbutton", { name: "Max" }).fill("80")
	await sheet.getByRole("button", { name: "Apply", exact: true }).click()
	await sheet.getByRole("button", { name: /Guests .*20, 80/ }).click()
	await sheet.getByRole("button", { name: "Comparison", exact: true }).click()
	await page.getByRole("menuitemradio", { name: "greater than", exact: true }).click()
	await expect(sheet.getByRole("spinbutton", { name: "Max" })).toHaveCount(0)
	await sheet.getByRole("button", { name: "Apply", exact: true }).click()
	await expect(sheet.getByRole("button", { name: "Guests greater than 20" })).toBeVisible()
	await sheet.getByRole("button", { name: "Tag Any" }).click()
	await sheet.getByPlaceholder("Add a tag and press Enter").fill("priority")
	await sheet.getByPlaceholder("Add a tag and press Enter").press("Enter")
	await sheet.getByRole("button", { name: "Apply", exact: true }).click()
	await expect(sheet.getByRole("button", { name: /Tag .*priority/ })).toBeVisible()
	await sheet.getByRole("button", { name: "Date Any" }).click()
	await sheet.getByRole("combobox", { name: "Choose a date" }).click()
	await expect(page.getByRole("grid").first()).toBeVisible()
	await expect(page.getByRole("grid")).toHaveCount(1)
	const calendarBounds = await page.getByRole("grid").boundingBox()
	expect(calendarBounds!.x + calendarBounds!.width).toBeLessThanOrEqual(390)
	// Base UI uses visually hidden role=button focus sentinels for WebKit.
	// Audit the actual calendar controls, excluding only those library sentinels.
	expect((await new AxeBuilder({ page }).include("dialog[open]").exclude("[data-base-ui-focus-guard]").analyze()).violations).toEqual([])
	await page.keyboard.press("Escape")
	await expect(sheet).toBeVisible()
	await sheet.getByRole("button", { name: "Back to filters" }).click()
	await sheet.getByRole("button", { name: "Clear filters", exact: true }).click()
	await expect(sheet).toContainText("No filters applied")
	await sheet.getByRole("button", { name: "Done", exact: true }).click()
	await page.getByRole("button", { name: "Show pending state" }).click()
	await expect(page.getByRole("button", { name: "Filters", exact: true })).toBeDisabled()
	await page.getByRole("button", { name: "Resume filtering" }).click()
	await expect(page.getByRole("button", { name: "Filters", exact: true })).toBeEnabled()
})
