/** Media library async states: a failed fetch retries with its current filters, and empty states recover. */
import { expect, test } from "@playwright/test"

import { url } from "./routes"

test("a failed fetch retries the current search, type, collection and sort", async ({ page }) => {
	const errors: string[] = []
	page.on("pageerror", error => errors.push(error.message))
	await page.goto(url("/media-library"))
	const demo = page.locator("#async-library")
	await expect(demo).toBeVisible({ timeout: 3000 })
	const results = demo.locator(".media-library--results")
	await expect(demo.getByRole("button", { name: "Select: granary-interior.jpg", exact: true })).toBeVisible()
	await demo.getByRole("textbox", { name: "Search assets…" }).fill("granary")
	await demo.getByRole("tab", { name: "Images", exact: true }).click()
	await demo.getByRole("combobox", { name: "Collection", exact: true }).click()
	await page.getByRole("option", { name: "Venues", exact: true }).click()
	await demo.getByRole("combobox", { name: "Sort", exact: true }).click()
	await page.getByRole("option", { name: "Name", exact: true }).click()
	await expect(results).toHaveAttribute("aria-busy", "false")
	await demo.getByRole("button", { name: "Select: granary-interior.jpg", exact: true }).click()
	await demo.getByRole("button", { name: "Simulate failure", exact: true }).click()
	await expect(results).toHaveAttribute("aria-busy", "true")
	await expect(demo.getByRole("status").filter({ hasText: "Loading assets…" })).toBeVisible()
	const alert = demo.getByRole("alert")
	await expect(alert).toContainText("Could not refresh assets")
	await expect(demo.locator(".media-library-card--component")).toHaveCount(2)
	await alert.getByRole("button", { name: "Try again", exact: true }).click()
	await expect(results).toHaveAttribute("aria-busy", "true")
	await expect(results).toHaveAttribute("aria-busy", "false")
	await expect(alert).toHaveCount(0)
	await expect(demo.getByRole("textbox", { name: "Search assets…" })).toHaveValue("granary")
	await expect(demo.getByRole("tab", { name: "Images", exact: true })).toHaveAttribute("aria-selected", "true")
	await expect(demo.getByRole("combobox", { name: "Collection", exact: true })).toContainText("Venues")
	await expect(demo.getByRole("combobox", { name: "Sort", exact: true })).toContainText("Name")
	await expect(demo.locator(".media-library-card--component")).toHaveCount(2)
	await expect(demo.locator(".media-library-card--component").first()).toContainText("granary-interior.jpg")
	await expect(demo.getByRole("button", { name: "Deselect: granary-interior.jpg", exact: true })).toHaveAttribute("aria-pressed", "true")
	await demo.getByRole("button", { name: "Use selected", exact: true }).click()
	await expect(demo.getByRole("status").filter({ hasText: "Attached 1 asset" })).toBeVisible()
	expect(errors).toEqual([])
})

test("empty and no-match states recover on a narrow screen", async ({ page }) => {
	await page.setViewportSize({ width: 390, height: 844 })
	await page.goto(url("/media-library"))
	const demo = page.locator("#async-library")
	await expect(demo).toBeVisible({ timeout: 3000 })
	await expect(demo.getByRole("button", { name: "Select: granary-interior.jpg", exact: true })).toBeVisible()
	await demo.getByRole("textbox", { name: "Search assets…" }).fill("missing-asset")
	await expect(demo.getByText("No assets match", { exact: true })).toBeVisible()
	await demo.locator(".media-library-empty-state--component").getByRole("button", { name: "Clear filters" }).click()
	await expect(demo.locator(".media-library-card--component")).toHaveCount(6)
	await demo.getByRole("button", { name: "Show empty library", exact: true }).click()
	await expect(demo.getByText("Nothing here yet", { exact: true })).toBeVisible()
	await demo.getByRole("button", { name: "Load sample assets", exact: true }).click()
	await expect(demo.locator(".media-library-card--component")).toHaveCount(6)
	const box = await demo.boundingBox()
	/* Within the 390px viewport, allowing 1px of rounding. */
	expect(box!.x).toBeGreaterThanOrEqual(0)
	expect(box!.x + box!.width).toBeLessThanOrEqual(391)
	const overflowing = await demo.evaluate(element => [...element.querySelectorAll("*")].some(child => {
		const bounds = child.getBoundingClientRect()
		return bounds.width > 0 && (bounds.left < -1 || bounds.right > window.innerWidth + 1)
	}))
	expect(overflowing).toBe(false)
})
