// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly cell: string
	readonly cellCaret: string
	readonly cellIcon: string
	readonly cellInert: string
	readonly cellText: string
	readonly cellValueRow: string
	readonly content: string
	readonly state: string
	readonly stateContent: string
	readonly trigger: string
}
export default styles
