// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly actions: string
	readonly floating: string
	readonly inline: string
	readonly root: string
	readonly summary: string
}
export default styles
