// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly actions: string
	readonly notice: string
	readonly titleRow: string
	readonly titleText: string
	readonly toneIcon: string
}
export default styles
