// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly controlInput: string
	readonly controlRow: string
	readonly controls: string
	readonly empty: string
	readonly exportBlock: string
	readonly exportBlockHeader: string
	readonly exportCode: string
	readonly exportFooter: string
	readonly field: string
	readonly fieldLabel: string
	readonly fields: string
	readonly layout: string
	readonly layoutWithPreview: string
	readonly minWidth: string
	readonly monoInput: string
	readonly numberInput: string
	readonly preview: string
	readonly previewCheck: string
	readonly providerSettings: string
	readonly root: string
	readonly rootScoped: string
	readonly settingsGrid: string
	readonly toolbar: string
}
export default styles
