// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly body: string
	readonly bodyWrap: string
	readonly counts: string
	readonly footerSlot: string
	readonly mount: string
	readonly placeholder: string
	readonly root: string
	readonly source: string
	readonly toolbar: string
	readonly toolbarButton: string
	readonly toolbarRule: string
	readonly toolbarTrailing: string
}
export default styles
