// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly group: string
	readonly indicator: string
	readonly item: string
	readonly itemText: string
	readonly label: string
	readonly optionDescription: string
	readonly optionIcon: string
	readonly optionText: string
	readonly popup: string
	readonly positioner: string
	readonly scrollArrow: string
	readonly scrollArrowDown: string
	readonly scrollArrowUp: string
	readonly separator: string
	readonly trigger: string
	readonly triggerIcon: string
	readonly value: string
}
export default styles
