// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly actionsBar: string
	readonly actionsBarSticky: string
	readonly actionsLayout: string
	readonly actionsLeading: string
	readonly actionsRow: string
	readonly actionsTrailing: string
	readonly errorSummary: string
	readonly field: string
	readonly fieldHorizontal: string
	readonly fieldHorizontalBody: string
	readonly group: string
	readonly groupLegend: string
	readonly label: string
	readonly required: string
	readonly section: string
	readonly submitSpinner: string
	readonly summaryList: string
}
export default styles
