// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly alignCenter: string
	readonly alignEnd: string
	readonly alignStart: string
	readonly body: string
	readonly caption: string
	readonly cell: string
	readonly container: string
	readonly empty: string
	readonly footer: string
	readonly head: string
	readonly headSort: string
	readonly headSortIcon: string
	readonly header: string
	readonly row: string
	readonly table: string
	readonly wrap: string
}
export default styles
