// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly filters: string
	readonly frame: string
	readonly frameContent: string
	readonly frameFooter: string
	readonly frameToolbar: string
	readonly pagination: string
	readonly shell: string
	readonly shellContent: string
	readonly shellRegion: string
	readonly toolbar: string
	readonly toolbarActions: string
	readonly toolbarInner: string
	readonly toolbarLeading: string
	readonly topbar: string
	readonly viewSelect: string
}
export default styles
