// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly actionStrip: string
	readonly actionStripBetween: string
	readonly actionStripEnd: string
	readonly actionStripFullPrimary: string
	readonly actionStripSeparated: string
	readonly alert: string
	readonly collapsible: string
	readonly content: string
	readonly description: string
	readonly expandToggle: string
	readonly expanded: string
	readonly footer: string
	readonly footerDivider: string
	readonly header: string
	readonly headerControls: string
	readonly headerDivider: string
	readonly icon: string
	readonly media: string
	readonly primaryAction: string
	readonly root: string
	readonly surfaceBordered: string
	readonly surfaceCard: string
	readonly surfaceFlat: string
	readonly surfaceFramed: string
	readonly title: string
	readonly titleInfo: string
	readonly titleRow: string
	readonly titleSuffix: string
}
export default styles
