// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly body: string
	readonly cards: string
	readonly columns2: string
	readonly columns3: string
	readonly footer: string
	readonly grid: string
	readonly header: string
	readonly mono: string
	readonly recommendation: string
	readonly recommendations: string
	readonly root: string
	readonly sectionFooter: string
	readonly sectionHeading: string
	readonly submitError: string
	readonly surface: string
	readonly widthFull: string
	readonly widthHalf: string
	readonly widthThird: string
}
export default styles
