// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly actions: string
	readonly layout: string
	readonly layoutBody: string
	readonly layoutContent: string
	readonly layoutHeader: string
	readonly layoutMeasure: string
	readonly layoutRail: string
	readonly layoutSidebar: string
	readonly metadata: string
	readonly nav: string
	readonly navFooter: string
	readonly navGroup: string
	readonly navGroupHead: string
	readonly navGroups: string
	readonly navItem: string
	readonly navItems: string
	readonly navProgress: string
	readonly navStatusIcon: string
	readonly recordHeader: string
	readonly secondary: string
	readonly strip: string
	readonly stripActions: string
	readonly stripHead: string
	readonly stripItem: string
	readonly stripList: string
	readonly titleSuffix: string
}
export default styles
