// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly confirmIcon: string
	readonly content: string
	readonly mono: string
	readonly root: string
	readonly trigger: string
	readonly triggerCompact: string
	readonly truncateRoot: string
}
export default styles
