// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly controls: string
	readonly controlsOverlay: string
	readonly directional: string
	readonly dot: string
	readonly dots: string
	readonly dotsPill: string
	readonly root: string
	readonly slide: string
	readonly vertical: string
	readonly viewport: string
}
export default styles
