// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly buttons: string
	readonly labelHidden: string
	readonly labelResponsive: string
	readonly linkButton: string
	readonly triggerLabel: string
}
export default styles
