// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly grip: string
	readonly group: string
	readonly handle: string
	readonly panel: string
}
export default styles
