// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly disclosure: string
	readonly logo: string
	readonly userChevron: string
	readonly userIdentity: string
	readonly userTrigger: string
	readonly workspaceChevron: string
	readonly workspaceMark: string
	readonly workspaceTrigger: string
}
export default styles
