// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly badge: string
	readonly count: string
	readonly fallback: string
	readonly group: string
	readonly image: string
	readonly root: string
}
export default styles
