// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly band: string
	readonly bandActions: string
	readonly bandText: string
	readonly body: string
	readonly calendar: string
	readonly caption: string
	readonly captionRange: string
	readonly cell: string
	readonly day: string
	readonly grid: string
	readonly header: string
	readonly monthCaption: string
	readonly monthCell: string
	readonly monthColumn: string
	readonly monthGrid: string
	readonly months: string
	readonly navButton: string
	readonly presets: string
	readonly row: string
	readonly time: string
	readonly timeSegment: string
	readonly timeSeparator: string
	readonly trigger: string
	readonly triggerClear: string
	readonly triggerFrame: string
	readonly triggerFrameClearable: string
	readonly triggerIcon: string
	readonly triggerPlaceholder: string
	readonly weekday: string
}
export default styles
