// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly addon: string
	readonly alignBlockEnd: string
	readonly alignBlockStart: string
	readonly alignInlineEnd: string
	readonly alignInlineStart: string
	readonly button: string
	readonly buttonIcon: string
	readonly control: string
	readonly controlTextarea: string
	readonly root: string
	readonly text: string
}
export default styles
