// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly content: string
	readonly description: string
	readonly footer: string
	readonly header: string
	readonly insetFlush: string
	readonly positioner: string
	readonly title: string
}
export default styles
