// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly container: string
	readonly gutterLg: string
	readonly gutterMd: string
	readonly gutterNone: string
	readonly gutterSm: string
	readonly max2Xl: string
	readonly maxFull: string
	readonly maxLg: string
	readonly maxMd: string
	readonly maxSm: string
	readonly maxXl: string
	readonly pageViewport: string
	readonly section: string
	readonly twoColumn: string
	readonly twoColumnAside: string
	readonly twoColumnAsideStart: string
	readonly twoColumnAsideSticky: string
	readonly twoColumnFooter: string
	readonly twoColumnHeader: string
	readonly twoColumnMain: string
}
export default styles
