// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly action: string
	readonly description: string
	readonly root: string
	readonly title: string
	readonly variantInverse: string
}
export default styles
