// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly doc: string
	readonly docBack: string
	readonly docDot: string
	readonly docFront: string
	readonly docStatus: string
	readonly docs: string
	readonly glass: string
	readonly inbox: string
	readonly inboxCheck: string
	readonly inboxDot: string
	readonly inboxLines: string
	readonly inboxLip: string
	readonly inboxRow: string
	readonly inboxTray: string
	readonly lineNarrow: string
	readonly lineShort: string
	readonly lineWide: string
	readonly stack: string
	readonly stackBack: string
	readonly stackFade: string
	readonly stackFront: string
	readonly stackLines: string
	readonly stackMid: string
	readonly stackThumb: string
	readonly userCentre: string
	readonly userLeft: string
	readonly userRight: string
	readonly users: string
}
export default styles
