// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly actions: string
	readonly bordered: string
	readonly content: string
	readonly description: string
	readonly media: string
	readonly mediaIcon: string
	readonly mediaIconSoft: string
	readonly mediaIllustration: string
	readonly padDefault: string
	readonly padSm: string
	readonly root: string
}
export default styles
