// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly alertMeta: string
	readonly alertMetaItem: string
	readonly alertMetaLabel: string
	readonly alertMetaValue: string
	readonly state: string
	readonly stateIcon: string
	readonly stateIconError: string
	readonly stateSpinner: string
}
export default styles
