// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly inner: string
	readonly root: string
	readonly toneDestructive: string
	readonly toneInfo: string
	readonly toneSuccess: string
	readonly toneWarning: string
}
export default styles
