// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly brand: string
	readonly breadcrumbs: string
	readonly center: string
	readonly content: string
	readonly crumbBar: string
	readonly crumbTrail: string
	readonly crumbTrigger: string
	readonly header: string
	readonly left: string
	readonly notificationBody: string
	readonly notificationRow: string
	readonly notificationText: string
	readonly notificationTone: string
	readonly notificationsEmpty: string
	readonly notificationsHead: string
	readonly notificationsList: string
	readonly right: string
	readonly search: string
	readonly searchHint: string
	readonly searchIcon: string
	readonly searchLabel: string
	readonly tool: string
	readonly toolBadge: string
	readonly toolSurface: string
	readonly userChevron: string
	readonly userIdentity: string
	readonly userTrigger: string
}
export default styles
