// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly credentialBody: string
	readonly credentialHeader: string
	readonly credentialList: string
	readonly credentialToggle: string
	readonly role: string
	readonly roleGroup: string
	readonly roleHeader: string
	readonly roleHeaderActions: string
	readonly roleIdentity: string
	readonly roleMark: string
	readonly rolePermission: string
	readonly rolePermissions: string
	readonly sensitive: string
	readonly sensitiveAction: string
	readonly sensitiveBody: string
	readonly sensitiveRow: string
}
export default styles
