// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly checklist: string
	readonly checklistProgress: string
	readonly checklistProgressHead: string
	readonly checklistRoot: string
	readonly indicator: string
	readonly titleDone: string
}
export default styles
