// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly choiceItem: string
	readonly content: string
	readonly indicator: string
	readonly item: string
	readonly itemBody: string
	readonly itemDescription: string
	readonly itemIcon: string
	readonly itemLabel: string
	readonly itemTrailing: string
	readonly itemWithDescription: string
	readonly label: string
	readonly positioner: string
	readonly separator: string
	readonly shortcut: string
	readonly subContent: string
	readonly subTriggerIcon: string
}
export default styles
