// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly colorNative: string
	readonly colorPicker: string
	readonly colorRoot: string
	readonly colorSwatch: string
	readonly colorText: string
	readonly phoneNumber: string
	readonly phonePrefix: string
	readonly phoneRoot: string
	readonly slider: string
	readonly sliderControl: string
	readonly sliderMd: string
	readonly sliderRange: string
	readonly sliderRoot: string
	readonly sliderThumb: string
	readonly sliderTrack: string
	readonly sliderValue: string
	readonly tag: string
	readonly tagRemove: string
	readonly tagsClear: string
	readonly tagsFooter: string
	readonly tagsInput: string
	readonly tagsOverLimit: string
	readonly tagsShell: string
}
export default styles
