// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly bare: string
	readonly body: string
	readonly close: string
	readonly description: string
	readonly footer: string
	readonly header: string
	readonly placementBlockEnd: string
	readonly placementBlockStart: string
	readonly placementCenter: string
	readonly placementInlineEnd: string
	readonly placementInlineStart: string
	readonly root: string
	readonly title: string
}
export default styles
