// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly belowCard: string
	readonly brand: string
	readonly brandLogo: string
	readonly brandText: string
	readonly card: string
	readonly cardMedia: string
	readonly link: string
	readonly linkButton: string
	readonly links: string
	readonly linksIcon: string
	readonly root: string
	readonly shell: string
	readonly shellAlignStart: string
	readonly sizeLg: string
	readonly sizeSm: string
	readonly split: string
	readonly splitContainer: string
	readonly splitForm: string
	readonly splitPanel: string
	readonly splitPanelStacked: string
	readonly surface: string
}
export default styles
