// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly group: string
	readonly root: string
	readonly size2Xl: string
	readonly sizeBase: string
	readonly sizeLg: string
	readonly sizeSm: string
	readonly sizeXl: string
	readonly sub: string
	readonly truncate: string
}
export default styles
