// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly body: string
	readonly card: string
	readonly dialogFooter: string
	readonly sections: string
	readonly summary: string
	readonly summaryValue: string
	readonly viewAction: string
}
export default styles
