#!/usr/bin/env node
/*
 * Installs the themelia-ui agent skill (which component to use, its exact import, what to
 * avoid) into a project's .agents/ and/or .claude/ skills. Offline: reads the copy shipped
 * in this package. Replaces a previous install atomically; never a hand-written skill.
 *   node node_modules/themelia-ui/scripts/consumer/install-skill.mjs --project=. [--target=agents|claude|both]
 */
import {
  cpSync, existsSync, mkdirSync, readFileSync, readdirSync, realpathSync, renameSync, rmSync,
  statSync,
} from 'node:fs'
import { dirname, join, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
/** scripts/consumer/ → the package root. */
export const PACKAGE_ROOT = resolve(HERE, '..', '..')
export const SOURCE = join(PACKAGE_ROOT, '.agents/skills/themelia-ui')

/**
 * The line that marks a destination as ours to replace; a SKILL.md without it was written
 * by hand and is never overwritten. gen-agent-skill.mjs writes the same string.
 */
export const GENERATED_MARKER = '<!-- GENERATED by themelia-ui/scripts/gen-agent-skill.mjs -->'

export const TARGET_DIRECTORIES = {
  agents: '.agents/skills/themelia-ui',
  claude: '.claude/skills/themelia-ui',
}

/** Whether a destination may be replaced: absent, or carrying our marker. */
export function mayOverwrite(destination) {
  const skill = join(destination, 'SKILL.md')
  if (!existsSync(skill)) return true
  return readFileSync(skill, 'utf8').includes(GENERATED_MARKER)
}

export function installSkill({ project = '.', target = 'both', source = SOURCE } = {}) {
  const targets = target === 'both' ? ['agents', 'claude'] : [target]
  if (targets.some((name) => !(name in TARGET_DIRECTORIES))) {
    throw new Error(`unknown --target=${target}; expected agents, claude or both`)
  }
  if (!existsSync(source)) throw new Error(`the packaged skill is missing at ${source}`)

  const nonce = `${process.pid}-${Date.now()}`
  const destinations = targets.map((name, index) => {
    const destination = resolve(project, TARGET_DIRECTORIES[name])
    return {
      name,
      destination,
      stage: `${destination}.installing-${nonce}-${index}`,
      backup: `${destination}.backup-${nonce}-${index}`,
      committed: false,
      hadExisting: existsSync(destination),
    }
  })

  /* Preflight every target before writing any of them. */
  for (const { destination } of destinations) {
    if (resolve(source) === destination) {
      throw new Error(`source and destination are the same directory: ${destination}`)
    }
    if (!mayOverwrite(destination)) {
      throw new Error(
        `${relative(process.cwd(), destination)} holds a SKILL.md this package did not write.\n` +
          '  Move it aside, or install only the other target with --target=agents|claude.',
      )
    }
  }

  try {
    for (const item of destinations) {
      mkdirSync(dirname(item.destination), { recursive: true })
      cpSync(source, item.stage, { recursive: true })
    }
    for (const item of destinations) {
      if (item.hadExisting) renameSync(item.destination, item.backup)
      renameSync(item.stage, item.destination)
      item.committed = true
    }
    for (const item of destinations) rmSync(item.backup, { recursive: true, force: true })
    return destinations.map(({ destination }) => destination)
  } catch (error) {
    for (const item of [...destinations].reverse()) {
      rmSync(item.stage, { recursive: true, force: true })
      if (item.committed) rmSync(item.destination, { recursive: true, force: true })
      if (existsSync(item.backup)) renameSync(item.backup, item.destination)
    }
    throw error
  }
}

/** Every file under a directory, relative and sorted — for tests and for the summary. */
export function listFiles(root) {
  const out = []
  const walk = (dir) => {
    for (const entry of readdirSync(dir)) {
      const full = join(dir, entry)
      if (statSync(full).isDirectory()) walk(full)
      else out.push(relative(root, full))
    }
  }
  if (existsSync(root)) walk(root)
  return out.sort()
}

/*
 * Run or imported? Compared via realpath: `process.argv[1]` and `import.meta.url` disagree
 * across symlinks (macOS `/tmp`, pnpm's store), and the script would silently do nothing.
 */
function runFromCommandLine(moduleUrl) {
  if (!process.argv[1]) return false
  const real = (path) => {
    try {
      return realpathSync(path)
    } catch {
      return resolve(path)
    }
  }
  return real(process.argv[1]) === real(fileURLToPath(moduleUrl))
}

const invokedDirectly = runFromCommandLine(import.meta.url)
if (invokedDirectly) {
  const USAGE = `usage: install-skill.mjs [--project=<directory>] [--target=agents|claude|both]

Copies the packaged themelia-ui consumer skill into a project. Existing generated
copies are replaced atomically; a same-named hand-written skill is never overwritten.`
  try {
    const options = { project: '.', target: 'both' }
    for (const argument of process.argv.slice(2)) {
      if (argument === '--help') {
        console.log(USAGE)
        process.exit(0)
      }
      const match = argument.match(/^--(project|target)=(.+)$/)
      if (!match) throw new Error(`unknown argument ${argument}\n\n${USAGE}`)
      options[match[1]] = match[2]
    }
    const installed = installSkill(options)
    for (const destination of installed) {
      console.log(`installed ${listFiles(destination).length} file(s) into ${relative(process.cwd(), destination) || '.'}`)
    }
  } catch (error) {
    console.error(`FAIL install-skill — ${error.message}`)
    process.exit(1)
  }
}
