// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly badge: string
	readonly bodyWithMedallion: string
	readonly bodyWithMedia: string
	readonly content: string
	readonly header: string
	readonly heading: string
	readonly icon: string
	readonly item: string
	readonly media: string
	readonly mediaMedallion: string
	readonly panel: string
	readonly root: string
	readonly row: string
	readonly rowWithMedia: string
	readonly surfaceBordered: string
	readonly surfaceCard: string
	readonly surfaceFlat: string
	readonly titleLine: string
	readonly trigger: string
}
export default styles
