/*
 * Writes src/preview/generated/gallery.json: one card per preview page, joining the page's
 * `summary` with its module's `chooseWhen`/`avoidWhen`. Module guidance appears only on the
 * module's canonical documentation route, not on supplemental pages.
 * Reads component-index.json: run gen-consumer-docs first. The gallery takes each card's tier
 * from the route table at runtime.
 */
import { readFileSync, mkdirSync } from 'node:fs'
import { writeIfChanged } from './lib/write-if-changed.mjs'

import { previewPages } from './lib/preview-pages.mjs'

const OUT = 'src/preview/generated/gallery.json'

const index = JSON.parse(readFileSync('docs/generated/component-index.json', 'utf8'))

/** published subpath → the module record that owns it */
const modules = new Map()
for (const record of index.modules) {
  if (record.import) modules.set(record.import, record)
}

const cards = []
for (const page of previewPages()) {
  /* Exact subpath, else the longest published module path the page's import starts with. */
  let owner = modules.get(page.subpath) ?? null
  if (!owner) {
    for (const [subpath, record] of modules) {
      if (!page.subpath.startsWith(`${subpath}/`)) continue
      if (!owner || subpath.length > owner.import.length) owner = record
    }
  }

  cards.push({
    title: page.title,
    summary: page.summary,
    route: page.preview,
    import: page.subpath,
    exports: page.exports,
    keywords: page.keywords,
    module: owner?.id ?? null,
    chooseWhen: owner?.documentation?.endsWith(`(${page.preview})`) ? owner.chooseWhen ?? null : null,
    avoidWhen: owner?.documentation?.endsWith(`(${page.preview})`) ? owner.avoidWhen ?? null : null,
  })
}

cards.sort((a, b) => a.title.localeCompare(b.title))

mkdirSync('src/preview/generated', { recursive: true })
writeIfChanged(
  OUT,
  `${JSON.stringify(
    {
      note:
        'Generated by scripts/gen-gallery.mjs. Each card is one preview page joined to the ' +
        'selection guidance of the module it imports from. Module-level guidance appears ' +
        'only on that module\'s canonical documentation route, never on a supplemental page.',
      cards,
    },
    null,
    2,
  )}\n`,
)

const guided = cards.filter((card) => card.chooseWhen).length
console.log(
  `gen:gallery — ${cards.length} cards, ${guided} carrying selection guidance`,
)
