/*
 * Generates the aggregate barrels (base, patterns, admin/patterns) as pure re-exports of the
 * hand-authored family barrels, so a new family is never left out, plus the root src/index.ts.
 * Family barrels stay hand-written: they decide what a component makes public.
 */
import { readdirSync, existsSync, readFileSync, writeFileSync } from 'node:fs'

const HEADER = '// GENERATED by scripts/gen-barrels.mjs — do not edit.\n'

function subBarrels(layer) {
  const dir = `src/components/${layer}`
  return readdirSync(dir, { withFileTypes: true })
    .filter((e) => e.isDirectory() && existsSync(`${dir}/${e.name}/index.ts`))
    .map((e) => e.name)
    .sort()
}

function write(path, body) {
  const next = HEADER + body
  if (existsSync(path) && readFileSync(path, 'utf8') === next) return false
  writeFileSync(path, next)
  return true
}

let written = 0

/* Layer barrels serve internal and preview imports; package.json exports only exact families. */
const base = subBarrels('base')
if (write('src/components/base/index.ts', base.map((n) => `export * from "./${n}"`).join('\n') + '\n')) written++

/* Optional: the generator must run cleanly before a profile's first family lands. */
const patterns = existsSync('src/components/patterns') ? subBarrels('patterns') : []
if (patterns.length && write('src/components/patterns/index.ts', patterns.map((n) => `export * from "./${n}"`).join('\n') + '\n')) written++

/* The admin profile's own aggregate, one level deeper: admin/patterns/<family>. */
const adminPatterns = existsSync('src/components/admin/patterns') ? subBarrels('admin/patterns') : []
if (adminPatterns.length && write('src/components/admin/patterns/index.ts', adminPatterns.map((n) => `export * from "./${n}"`).join('\n') + '\n')) written++

/*
 * The root barrel is the foundation only (provider and display primitives, both peer-free).
 * Re-exporting a layer here would make `import { Button } from "themelia-ui"` resolve every
 * optional peer; components come from their exact subpaths.
 */
const root = [
  'export * from "./components/primitives"',
  'export * from "./lib/ui-provider"',
].join('\n')
if (write('src/index.ts', root + '\n')) written++

const expected = 2 + (patterns.length ? 1 : 0) + (adminPatterns.length ? 1 : 0)
console.log(`barrels: ${written} written, ${expected - written} already current (base ${base.length}, patterns ${patterns.length}, admin/patterns ${adminPatterns.length})`)
