// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly button: string
	readonly group: string
	readonly input: string
	readonly link: string
	readonly root: string
	readonly separator: string
}
export default styles
