// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly actions: string
	readonly actionsTrigger: string
	readonly board: string
	readonly column: string
	readonly columnContent: string
	readonly handle: string
	readonly item: string
	readonly overlay: string
	readonly root: string
}
export default styles
