// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly currencyColumn: string
	readonly dimensions: string
	readonly field: string
	readonly grow: string
	readonly numericInput: string
	readonly row: string
	readonly separator: string
	readonly stepperAdornment: string
	readonly stepperButton: string
	readonly stepperGroup: string
	readonly stepperInput: string
	readonly subLabel: string
	readonly unitColumn: string
}
export default styles
