// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly band: string
	readonly body: string
	readonly content: string
	readonly description: string
	readonly footer: string
	readonly header: string
	readonly icon: string
	readonly item: string
	readonly list: string
	readonly loading: string
	readonly loadingIcon: string
	readonly status: string
}
export default styles
