// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly breadcrumb: string
	readonly breadcrumbCurrent: string
	readonly breadcrumbItem: string
	readonly breadcrumbLink: string
	readonly breadcrumbSeparator: string
	readonly pageHeading: string
	readonly pageHeadingActions: string
	readonly pageHeadingBadges: string
	readonly pageHeadingBlock: string
	readonly pageHeadingChildren: string
	readonly pageHeadingCrumbs: string
	readonly pageHeadingDescription: string
	readonly pageHeadingGrid: string
	readonly pageHeadingHeadline: string
	readonly pageHeadingLeading: string
	readonly pageHeadingMain: string
	readonly pageHeadingPrefix: string
	readonly pageHeadingRow: string
	readonly pageHeadingSeparator: string
	readonly pageHeadingTitle: string
	readonly pageHeadingTitleRow: string
	readonly pagination: string
	readonly paginationArrowWord: string
	readonly paginationEllipsis: string
	readonly tab: string
	readonly tabBar: string
	readonly tabBarWrap: string
	readonly tabList: string
	readonly tabListEnclosed: string
	readonly tabPanel: string
	readonly tabRail: string
	readonly tabScroll: string
	readonly tabs: string
	readonly tabsPill: string
}
export default styles
