// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly actions: string
	readonly content: string
	readonly description: string
	readonly footer: string
	readonly group: string
	readonly header: string
	readonly listItem: string
	readonly media: string
	readonly mediaIcon: string
	readonly mediaImage: string
	readonly root: string
	readonly separator: string
	readonly surfaceBordered: string
	readonly surfaceMuted: string
	readonly title: string
}
export default styles
