// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly autocomplete: string
	readonly autocompleteAnchor: string
	readonly autocompleteField: string
	readonly autocompleteList: string
	readonly autocompleteResults: string
	readonly autocompleteRow: string
	readonly autocompleteTrigger: string
	readonly bottomLeft: string
	readonly bottomRight: string
	readonly control: string
	readonly controlButton: string
	readonly controlMenu: string
	readonly drawHandle: string
	readonly heightLg: string
	readonly heightMd: string
	readonly heightSm: string
	readonly map: string
	readonly markerIcon: string
	readonly popup: string
	readonly pulse: string
	readonly pulseDot: string
	readonly pulseRing: string
	readonly searchControl: string
	readonly shape: string
	readonly spin: string
	readonly surfaceFlush: string
	readonly surfaceFramed: string
	readonly tooltip: string
	readonly tooltipArrow: string
	readonly topLeft: string
	readonly topRight: string
}
export default styles
