// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly adaptive: string
	readonly bleed: string
	readonly cell: string
	readonly grid: string
	readonly split: string
	readonly stack: string
}
export default styles
