// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly body: string
	readonly empty: string
	readonly footer: string
	readonly handle: string
	readonly list: string
	readonly remove: string
	readonly root: string
	readonly row: string
	readonly rowCard: string
}
export default styles
