// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly byline: string
	readonly progressGroup: string
	readonly stepsBar: string
	readonly titleRow: string
}
export default styles
