// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly styleGhost: string
	readonly styleOutline: string
	readonly styleSolid: string
	readonly toneDestructive: string
	readonly toneInfo: string
	readonly toneNeutral: string
	readonly tonePrimary: string
	readonly toneSecondary: string
	readonly toneSuccess: string
	readonly toneWarning: string
}
export default styles
