// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly fullWidth: string
	readonly iconOnly: string
	readonly label: string
	readonly loadingLabel: string
	readonly root: string
	readonly textButton: string
}
export default styles
