// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly groupSeparator: string
	readonly groupSeparatorVertical: string
	readonly groupText: string
	readonly root: string
	readonly vertical: string
}
export default styles
