// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly appearanceGhost: string
	readonly appearanceOutline: string
	readonly appearanceSolid: string
}
export default styles
