// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly pair: string
	readonly primary: string
	readonly secondary: string
	readonly separator: string
	readonly stacked: string
}
export default styles
