// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly empty: string
	readonly inline: string
	readonly link: string
	readonly mono: string
	readonly numeric: string
	readonly root: string
	readonly secondary: string
}
export default styles
