// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly empty: string
	readonly placeholder: string
	readonly root: string
	readonly symbol: string
}
export default styles
