// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly action: string
	readonly actions: string
	readonly arrow: string
	readonly backdrop: string
	readonly chip: string
	readonly chipRemove: string
	readonly chips: string
	readonly chipsInput: string
	readonly empty: string
	readonly group: string
	readonly groupLabel: string
	readonly indicator: string
	readonly input: string
	readonly inputWrap: string
	readonly item: string
	readonly itemLabel: string
	readonly list: string
	readonly popup: string
	readonly popupSearch: string
	readonly popupSearchIcon: string
	readonly popupSearchInput: string
	readonly positioner: string
	readonly separator: string
	readonly status: string
	readonly trigger: string
	readonly triggerIcon: string
}
export default styles
