// GENERATED by scripts/gen-token-names.mjs — do not edit.
//
// Read from styles/theme/*.css, so the provider's typed surface and the ThemeTweaker's
// defaults cannot drift from the variables the stylesheet declares.

/** Colour variables a consumer may retheme, named without the leading `--`. */
export type SemanticToken =
	| "accent"
	| "accent-foreground"
	| "background"
	| "border"
	| "card"
	| "card-foreground"
	| "chart-1"
	| "chart-2"
	| "chart-3"
	| "chart-4"
	| "chart-5"
	| "destructive"
	| "destructive-foreground"
	| "foreground"
	| "info"
	| "info-foreground"
	| "input"
	| "link"
	| "muted"
	| "muted-foreground"
	| "overlay-backdrop"
	| "popover"
	| "popover-foreground"
	| "primary"
	| "primary-foreground"
	| "ring"
	| "secondary"
	| "secondary-foreground"
	| "sidebar"
	| "sidebar-accent"
	| "sidebar-accent-foreground"
	| "sidebar-border"
	| "sidebar-foreground"
	| "sidebar-ring"
	| "success"
	| "success-foreground"
	| "warning"
	| "warning-foreground"

/** Every theme variable. */
export type ThemeVariable =
	| "--accent"
	| "--accent-foreground"
	| "--background"
	| "--border"
	| "--border-width"
	| "--card"
	| "--card-foreground"
	| "--chart-1"
	| "--chart-2"
	| "--chart-3"
	| "--chart-4"
	| "--chart-5"
	| "--content-width"
	| "--control-height"
	| "--control-height-sm"
	| "--destructive"
	| "--destructive-foreground"
	| "--disabled-opacity"
	| "--duration"
	| "--duration-fast"
	| "--ease"
	| "--font-heading"
	| "--font-mono"
	| "--font-sans"
	| "--foreground"
	| "--gap"
	| "--gap-sm"
	| "--header-height"
	| "--icon-size"
	| "--icon-size-sm"
	| "--info"
	| "--info-foreground"
	| "--input"
	| "--link"
	| "--muted"
	| "--muted-foreground"
	| "--overlay-backdrop"
	| "--overlay-backdrop-filter"
	| "--padding"
	| "--padding-sm"
	| "--popover"
	| "--popover-foreground"
	| "--primary"
	| "--primary-foreground"
	| "--radius"
	| "--radius-pill"
	| "--radius-sm"
	| "--ring"
	| "--secondary"
	| "--secondary-foreground"
	| "--shadow"
	| "--shadow-lg"
	| "--sidebar"
	| "--sidebar-accent"
	| "--sidebar-accent-foreground"
	| "--sidebar-border"
	| "--sidebar-foreground"
	| "--sidebar-ring"
	| "--sidebar-width"
	| "--success"
	| "--success-foreground"
	| "--text-2xl"
	| "--text-base"
	| "--text-lg"
	| "--text-pxs"
	| "--text-scale"
	| "--text-sm"
	| "--text-xl"
	| "--text-xs"
	| "--tint"
	| "--tint-strong"
	| "--warning"
	| "--warning-foreground"
	| "--z-docked"
	| "--z-popover"
	| "--z-sticky"
	| "--z-toast"
	| "--z-tooltip"

/** Each theme variable's declared value; a colour is `light-dark(light, dark)`. */
export const THEME_DEFAULTS: Readonly<Record<ThemeVariable, string>> = {
	"--accent": "light-dark(oklch(0.97 0 0), oklch(0.33 0 0))",
	"--accent-foreground": "light-dark(oklch(0.205 0 0), oklch(0.985 0 0))",
	"--background": "light-dark(oklch(1 0 0), oklch(0.205 0 0))",
	"--border": "light-dark(oklch(0.922 0 0), oklch(1 0 0 / 10%))",
	"--border-width": "1px",
	"--card": "light-dark(oklch(1 0 0), oklch(0.25 0 0))",
	"--card-foreground": "light-dark(oklch(0.28 0 0), oklch(0.985 0 0))",
	"--chart-1": "light-dark(oklch(0.56 0.11 167), oklch(0.74 0.13 167))",
	"--chart-2": "light-dark(oklch(0.56 0.11 230), oklch(0.72 0.14 230))",
	"--chart-3": "light-dark(oklch(0.56 0.17 285), oklch(0.72 0.15 285))",
	"--chart-4": "light-dark(oklch(0.58 0.16 330), oklch(0.74 0.15 330))",
	"--chart-5": "light-dark(oklch(0.6 0.14 60), oklch(0.78 0.14 60))",
	"--content-width": "64rem",
	"--control-height": "2.125rem",
	"--control-height-sm": "1.875rem",
	"--destructive": "light-dark(oklch(0.5 0.245 27.325), oklch(0.74 0.158 22.216))",
	"--destructive-foreground": "light-dark(oklch(0.99 0 0), oklch(0.18 0.05 22))",
	"--disabled-opacity": "0.5",
	"--duration": "0ms",
	"--duration-fast": "0ms",
	"--ease": "cubic-bezier(0.23, 1, 0.32, 1)",
	"--font-heading": "initial",
	"--font-mono": "'Geist Mono', ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, 'Liberation Mono', monospace",
	"--font-sans": "'Geist', ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', sans-serif",
	"--foreground": "light-dark(oklch(0.28 0 0), oklch(0.985 0 0))",
	"--gap": "1rem",
	"--gap-sm": "0.5rem",
	"--header-height": "3.5rem",
	"--icon-size": "1rem",
	"--icon-size-sm": "0.75rem",
	"--info": "light-dark(oklch(0.45 0.214 276.966), oklch(0.72 0.14 250))",
	"--info-foreground": "light-dark(oklch(0.99 0 0), oklch(0.18 0.05 250))",
	"--input": "light-dark(oklch(0.73 0 0), oklch(1 0 0 / 28%))",
	"--link": "light-dark(oklch(0.462 0.1776 259.13), oklch(0.72 0.12 259.13))",
	"--muted": "light-dark(oklch(0.97 0 0), oklch(0.23 0 0))",
	"--muted-foreground": "light-dark(oklch(0.5 0 0), oklch(0.708 0 0))",
	"--overlay-backdrop": "oklch(0 0 0 / 0.5)",
	"--overlay-backdrop-filter": "none",
	"--padding": "1rem",
	"--padding-sm": "0.5rem",
	"--popover": "light-dark(oklch(1 0 0), oklch(0.28 0 0))",
	"--popover-foreground": "light-dark(oklch(0.28 0 0), oklch(0.985 0 0))",
	"--primary": "light-dark(oklch(0.45 0.124 167.35), oklch(0.7 0.13 167.35))",
	"--primary-foreground": "light-dark(oklch(0.985 0 0), oklch(0.18 0.03 167.35))",
	"--radius": "1rem",
	"--radius-pill": "999px",
	"--radius-sm": "0.5rem",
	"--ring": "light-dark(oklch(0.58 0 0), oklch(0.62 0 0))",
	"--secondary": "light-dark(oklch(0.97 0 0), oklch(0.25 0 0))",
	"--secondary-foreground": "light-dark(oklch(0.205 0 0), oklch(0.985 0 0))",
	"--shadow": "0 1px 2px 0 oklch(0 0 0 / 6%), 0 1px 1px -1px oklch(0 0 0 / 6%)",
	"--shadow-lg": "0 4px 8px -2px oklch(0 0 0 / 10%), 0 12px 24px -12px oklch(0 0 0 / 18%)",
	"--sidebar": "light-dark(oklch(0.96 0 0), oklch(0.16 0 0))",
	"--sidebar-accent": "light-dark(oklch(0.98 0 0), oklch(0.28 0 0))",
	"--sidebar-accent-foreground": "light-dark(oklch(0.205 0 0), oklch(0.985 0 0))",
	"--sidebar-border": "light-dark(oklch(0.922 0 0), oklch(1 0 0 / 10%))",
	"--sidebar-foreground": "light-dark(oklch(0.28 0 0), oklch(0.985 0 0))",
	"--sidebar-ring": "light-dark(oklch(0.58 0 0), oklch(0.62 0 0))",
	"--sidebar-width": "16rem",
	"--success": "light-dark(oklch(0.4 0.16 145), oklch(0.76 0.16 145))",
	"--success-foreground": "light-dark(oklch(0.985 0 0), oklch(0.18 0.05 145))",
	"--text-2xl": "1.5rem",
	"--text-base": "1rem",
	"--text-lg": "1.125rem",
	"--text-pxs": "0.8125rem",
	"--text-scale": "1",
	"--text-sm": "0.875rem",
	"--text-xl": "1.25rem",
	"--text-xs": "0.75rem",
	"--tint": "10%",
	"--tint-strong": "30%",
	"--warning": "light-dark(oklch(0.72 0.16 90), oklch(0.82 0.16 90))",
	"--warning-foreground": "light-dark(oklch(0.2 0.05 80), oklch(0.18 0.05 80))",
	"--z-docked": "20",
	"--z-popover": "50",
	"--z-sticky": "10",
	"--z-toast": "100",
	"--z-tooltip": "1000",
}
