// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly description: string
	readonly gridItem: string
	readonly gridLabel: string
	readonly infoTrigger: string
	readonly inline: string
	readonly inlineItem: string
	readonly inlineLabel: string
	readonly inlineSeparator: string
	readonly itemIcon: string
	readonly label: string
	readonly labelWrap: string
	readonly root: string
	readonly row: string
	readonly rowLabel: string
	readonly rowValue: string
	readonly rows: string
	readonly rowsDivided: string
	readonly title: string
	readonly titleSeparator: string
	readonly tooltip: string
	readonly value: string
}
export default styles
