// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly actionBar: string
	readonly actionBarLeading: string
	readonly actionBarSticky: string
	readonly actionBarTrailing: string
	readonly aside: string
	readonly content: string
	readonly headerAvatar: string
	readonly headerBadges: string
	readonly headerIcon: string
	readonly headerMetadata: string
	readonly layout: string
	readonly primary: string
	readonly section: string
	readonly sectionContent: string
	readonly sectionFooter: string
	readonly shell: string
	readonly stateSurface: string
}
export default styles
