// GENERATED by scripts/gen-css-types.mjs — do not edit.
declare const styles: {
	readonly alignCenter: string
	readonly alignLeft: string
	readonly alignRight: string
	readonly leadingLoose: string
	readonly leadingNone: string
	readonly leadingNormal: string
	readonly leadingRelaxed: string
	readonly leadingSnug: string
	readonly leadingTight: string
	readonly numeric: string
	readonly root: string
	readonly sizeBase: string
	readonly sizeDefault: string
	readonly sizeLg: string
	readonly sizePxs: string
	readonly sizeSm: string
	readonly sizeXl: string
	readonly sizeXs: string
	readonly sizeXxs: string
	readonly truncate: string
	readonly typeError: string
	readonly typeInverse: string
	readonly typeMain: string
	readonly typePrimary: string
	readonly typeSecondary: string
	readonly typeSuccess: string
	readonly weightBold: string
	readonly weightMedium: string
	readonly weightNormal: string
	readonly weightSemibold: string
}
export default styles
